/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.librarian;

import common.controller.BookController;
import common.controller.TaskController;
import entity.BorrowedInfo;
import entity.Copy;
import entity.ReturnInfo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * Một dialog ghi thông tin chi tiết trả
 * @author Raph
 */
public class ReturnDescriptionForm extends javax.swing.JDialog {

    /**
     * Creates new form Return
     *
     * @param parent
     * @param modal
     * @param bookId : mã sách
     * @param copyId : mã bản sao
     * @param bookName : tên sách
     * @param price : giá
     * @param id : mã người mượn
     * @param name : tên người mượn
     * @param borrowedInfoId : mã thông tin mượn
     * @param isNotExpired : có phải là hết hạn trả
     */
    public ReturnDescriptionForm(java.awt.Frame parent, boolean modal, String bookId, String copyId, String bookName, double price, int id, String name, int borrowedInfoId, boolean isNotExpired) {
        super(parent, modal);
        initComponents();
        setTitle("Chi tiết thông tin trả");
        setLocationRelativeTo(null);
        jLabelArlert.setVisible(false);
        configLabel(bookId, copyId, bookName, price, id, name);
        this.borrowedInforId = borrowedInfoId;
        if (!isNotExpired) {
            jLabelArlert.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelBookId = new javax.swing.JLabel();
        jLabelCopyId = new javax.swing.JLabel();
        jLabelBookName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelBorrowerId = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabelArlert = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jButtonOK1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel7.setFont(new java.awt.Font("UTM Copperplate", 1, 24)); // NOI18N
        jLabel7.setText("Chi tiết trả sách");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Tiêu đề");

        jLabel4.setText("Mã sách");

        jLabel5.setText("Mã bản sao");

        jLabel10.setText("Giá");

        jLabelBookId.setText("jLabel16");

        jLabelCopyId.setText("jLabel17");

        jLabelBookName.setText("jLabel18");

        jLabelPrice.setText("jLabel22");

        jLabel11.setText("Mã người mượn");

        jLabelBorrowerId.setText("jLabel23");

        jLabel12.setText("Tên");

        jLabelName.setText("jLabel24");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelBookId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(jLabelCopyId)
                                .addGap(58, 58, 58))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBookName)
                                    .addComponent(jLabelPrice))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBorrowerId)
                            .addComponent(jLabelName))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabelBookId)
                    .addComponent(jLabelCopyId))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelBookName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelBorrowerId))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelName))
                .addGap(31, 31, 31))
        );

        jLabel1.setText("Mô tả cuốn sách (tình trạng, vv...)");

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea);

        jLabelArlert.setForeground(new java.awt.Color(255, 0, 51));
        jLabelArlert.setText("Trễ hạn trả bản sao này");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Giá đền bù");

        jTextField.setText("0");

        jButtonOK1.setText("OK");
        jButtonOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOK1ActionPerformed(evt);
            }
        });

        jLabel8.setText("VND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButtonOK1)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelArlert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOK1ActionPerformed
        // TODO add your handling code here:
        String compensationPriceValue = jTextField.getText();
        Matcher matcher = Pattern.compile(".*\\D.*").matcher(compensationPriceValue);
        if (matcher.find()) {
            JOptionPane.showMessageDialog(this, "Định dạng không chính xác", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int borrowerId = Integer.valueOf(jLabelBorrowerId.getText());
        String copyId = jLabelCopyId.getText();
        String description = jTextArea.getText();
        double compesationPrice = Double.valueOf(compensationPriceValue);

        try {
            ReturnInfo infor = new ReturnInfo(borrowerId, copyId, description, compesationPrice);
            TaskController.getInstance().addReturnInfor(infor);
            BookController.getInstance().updateCopyStatus(copyId, Copy.AVAILABLE);
            BorrowedInfo borrowedInfo = TaskController.getInstance().getBorrowedInfor(borrowedInforId);
            int registId = borrowedInfo.getRegistrationInfoId();
            TaskController.getInstance().deleteBorrowedInfor(borrowedInforId);
            TaskController.getInstance().deleteRegistrationInfor(registId);

            JOptionPane.showMessageDialog(this, "Trả sách thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReturnDescriptionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        isHitOK = true;

    }//GEN-LAST:event_jButtonOK1ActionPerformed

    /**
     * Hàm thực hiện cấu hình label
     * @param bookId : mã sách
     * @param copyId : mã bản sao
     * @param bookName : tên sách
     * @param price : giá
     * @param id : mã người mượn
     * @param name : tên người mượn
     */
    private void configLabel(String bookId, String copyId, String bookName, double price, int id, String name) {
        displayBookId(bookId);
        displayCopyId(copyId);
        displayBookName(bookName);
        displayPrice(price);

        displayBorrowerId(id);
        displayBorrowerName(name);
    }

    /**
     * Hàm set label mã sách
     * @param bookId : mã sách 
     */
    private void displayBookId(String bookId) {
        this.jLabelBookId.setText(bookId);
    }

    /**
     * Hàm set label tên sách
     * @param bookName : tên sách
     */
    private void displayBookName(String bookName) {
        this.jLabelBookName.setText(bookName);
    }

    /**
     * Hàm set label mã bản sao
     * @param copyId : mã bản sao
     */
    private void displayCopyId(String copyId) {
        this.jLabelCopyId.setText(copyId);
    }

    /**
     * Hàm set label giá
     * @param price : giá
     */
    private void displayPrice(double price) {
        this.jLabelPrice.setText(String.valueOf(price));
    }

    /**
     * Hàm set label mã người mượn
     * @param id : mã người mượn
     */
    private void displayBorrowerId(int id) {
        this.jLabelBorrowerId.setText(String.valueOf(id));
    }

    /**
     * Hàm set label tên người mượn
     * @param name : tên người mượn
     */
    private void displayBorrowerName(String name) {
        this.jLabelName.setText(name);
    }

    /**
     * Hàm kiểm tra nhấn nút OK
     * @return true nếu nhấn, false ngược lại
     */
    public boolean hitOK() {
        return isHitOK;
    }

    private final int borrowedInforId;
    private boolean isHitOK = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelArlert;
    private javax.swing.JLabel jLabelBookId;
    private javax.swing.JLabel jLabelBookName;
    private javax.swing.JLabel jLabelBorrowerId;
    private javax.swing.JLabel jLabelCopyId;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
