/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.common;

import entity.Borrower;
import entity.Librarian;
import entity.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import user.controller.BorrowerController;
import user.controller.LibrarianController;
import user.controller.UserController;

/**
 * Lớp bao thông tin người dùng
 *
 * @author Raph
 */
public class UserDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailForm
     */
    public UserDetailForm() {
        initComponents();
        configLabel();
    }

    /**
     * Hàm cấu hình label
     */
    private void configLabel() {
        String username = MainForm.getUsername();

        try {
            User user = UserController.getInstance().getUserInfor(username);
            if(user ==  null){
                return;
            }
            
            if (BorrowerController.getInstance().checkBorrower(username)) {
                Borrower borrower = BorrowerController.getInstance().getBorrowerInfor(username);
                jLabelID.setText(borrower.getStudentId());
                jLabelPeriod.setText(borrower.getPeriod());

            } else if (LibrarianController.getInstance().checkLibrarian(username)){
                Librarian librarian = LibrarianController.getInstance().getLibrarianInfor(username);
                jLabelMSSV.setText("Ngày sinh:");
                jLabelID.setText(librarian.getBirthDay().toString());
                
                jLabelGDH.setVisible(false);
                jLabelPeriod.setVisible(false);
            } else {
                
                jLabelMSSV.setVisible(false);
                jLabelID.setVisible(false);
                jLabelGDH.setVisible(false);
                jLabelPeriod.setVisible(false);
            }

            jLabelName.setText(user.getName());
            jLabelGender.setText(user.isIsFemale() ? "Nữ" : "Nam");
            jLabelEmail.setText(user.getEmail());
            jLabelContact.setText(user.getContact());

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(UserDetailForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelContact = new javax.swing.JLabel();
        jLabelMSSV = new javax.swing.JLabel();
        jLabelGDH = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelPeriod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tên:");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Email:");

        jLabel5.setText("Liên hệ:");

        jLabelName.setText("null");

        jLabelGender.setText("null");

        jLabelEmail.setText("null");

        jLabelContact.setText("null");

        jLabelMSSV.setText("MSSV:");

        jLabelGDH.setText("Giai đoạn học:");

        jLabelID.setText("null");

        jLabelPeriod.setText("null");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGDH)
                    .addComponent(jLabelMSSV)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName)
                    .addComponent(jLabelGender)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelContact)
                    .addComponent(jLabelID)
                    .addComponent(jLabelPeriod))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelName))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelGender))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEmail))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMSSV)
                    .addComponent(jLabelID))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGDH)
                    .addComponent(jLabelPeriod))
                .addGap(41, 41, 41))
        );

        jLabel2.setFont(new java.awt.Font("UTM Copperplate", 1, 24)); // NOI18N
        jLabel2.setText("Thông tin cá nhân");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGDH;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMSSV;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPeriod;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
